### PR TITLE
adding CQConfigManager and TemplateEditor Clients

### PR DESCRIPTION
**Pull request by anagarwa**

### CODE REVIEW

**Comment by volteanu** [comment]
@anagarwa thanks for the proposed contribution! 
I think we need to clear out a few things before we move on with the detailed review of this.

1. The awaitility library adds a weight to the lib and we can't add it as a direct dependency. Test projects, OTOH, can use it without issues. We already have a lightweight `Polling` mechanism, so please use that to be inline with the other classes in the lib
2. Junit-jupiter - same here, the lib is currently built on junit4 (rules) and mixing both approaches will add to the jar size and make the maintenance more complex 
3. Constants class is exposed as an API of the lib and many things from there don't really make sense. Please clean it up and distribute the constants to the classes where they belong to
4. Let's split this PR in multiple, based on the individual functionalities introduced (e.g. one for CQConfigManagerClient and one for TemplateEditorClient). Like this we can focus on each change
5. Comments - this PR introduces a lot of public API and needs much more documentation for the users to understand how they can use it

**Comment by anagarwa** [comment]
@volteanu thanks for helping here.

> 2\. Junit-jupiter - same here, the lib is currently built on junit4 (rules) and mixing both approaches will add to the jar size and make the maintenance more complex

So can we push these changes about TestContentExtension and TestContentBuilder into some other repo, if not here to use this code ?

> 3\.Constants class is exposed as an API of the lib and many things from there don't really make sense. Please clean it up and distribute the constants to the classes where they belong to

What if the case is where we might need to duplicate the constant ? do we create a copy in each  class rather then having their own implementation ?

>4\.Let's split this PR in multiple, based on the individual functionalities introduced (e.g. one for CQConfigManagerClient and one for TemplateEditorClient). Like this we can focus on each change

okks let me try to create multiple PR with the problems statement to have a more focus approach for the review and hence more clean history the commits.

**Comment by anagarwa** [comment]
@volteanu I have created a new pr #53 to add the testing clients only. Can you please help in the review of them.
I will close this pr.

**Comment by volteanu** [comment]
Released in aem-cloud-testing-clients-0.7.0

**Pull request closed without merging**
