### PR TITLE
fix CQAssetsClient failing to retry binary upload (PUT) requests

### PR DESCRIPTION
**Pull request by alexkli**
Cloud blob store (Azure Blob Storage or S3) relatively frequently return temporary 503 errors that can be solved with a retry. The http client here is already retrying automatically, but retries fail with

```
Cannot retry request with a non-repeatable request entity
```

because it uses an `InputStreamEntity` which is non-repeatable as the input stream is already consumed after the first request.

The fix changes that to an `EntityTemplate` which will recreate the input stream on every retry.

Related issue: [CQ-4311192](https://jira.corp.adobe.com/browse/CQ-4311192).

### CODE REVIEW

**Comment by alexkli** [comment]
cc @volteanu @ireasor

**Comment by alexkli** [comment]
Ping @volteanu @dulvac @ireasor

This fixes a bug that improves test stability.

Not sure what to do with the codecov failure, CQAssetClient does not have any test coverage yet and I didn't have the time to work on that foundation.

**Review by dulvac — APPROVED** [review]

**Comment by dulvac** [comment]
I haven't tested this, but lgtm

**Comment by ireasor** [comment]
> Not sure what to do with the codecov failure, CQAssetClient does not have any test coverage yet and I didn't have the time to work on that foundation.

@dulvac is this a concern?  It looks like coverage in this repository is very low - I only see a handful of tests.  If so, I can log a ticket for someone to come in and add test coverage of this client.

**Comment by dulvac** [comment]
> @dulvac is this a concern? It looks like coverage in this repository is very low - I only see a handful of tests. If so, I can log a ticket for someone to come in and add test coverage of this client.

@ireasor , It would be nice if you contributed unit tests as well, but it shouldn't block this PR.
@volteanu , we're good to merge and release this?

**Comment by volteanu** [comment]
merged it as it is since I didn't find the time to address the coverage

**Comment by volteanu** [comment]
this has been included in `aem-cloud-testing-clients-0.6.1`

**Comment by alexkli** [comment]
Thanks!

**Pull request merged**
